services:
  bot:
    image: gambojo/telebotcore:latest
    container_name: bot
    environment:
      BOT_TOKEN: "bot's telegram token"
      ADMIN_IDS: "<telegram id's>"
      SUPPORT: "<support's telegram username"
    restart: unless-stopped
    volumes:
      - ./plugins:/app/plugins
    depends_on:
      plugin-downloader:
        condition: service_completed_successfully

  plugin-downloader:
    image: alpine:latest
    container_name: plugin-downloader
    working_dir: /app/plugins
    environment:
      PLUGIN_URLS: "https://github.com/gambojo/TeleBotPlugin.git" # example "https://plgn1.git,https://plgn2.git,.."
    command:
      - sh
      - -c
      - |
        apk add --no-cache git
        echo "Downloading plugins..."
        OLD_IFS=$$IFS
        IFS=','
        for url in $$PLUGIN_URLS; do
            echo "Downloading: $$url"
            git clone "$$url"
        done
        IFS=$$OLD_IFS
        echo "All plugins downloaded!"
    restart: "no"
    volumes:
      - ./plugins:/app/plugins
